modified the docker file

diff --git a/dockerfile/Dockerfile b/dockerfile/Dockerfile
--- a/dockerfile/Dockerfile
+++ b/dockerfile/Dockerfile
@@ -1,19 +1,28 @@
-# inherit the baidu sdk image
-FROM baiduxlab/sgx-rust:1.0.0
+FROM baiduxlab/sgx-rust:1.0.0 as runtime
 
-MAINTAINER enigmampc
+LABEL maintainer='info@enigma.co'
 
 WORKDIR /root
 
-RUN rm -rf /root/sgx
-
 # clone the rust-sgx-sdk baidu sdk v1.0.0
-
+RUN rm -rf /root/sgx
 RUN git clone https://github.com/baidu/rust-sgx-sdk.git sgx -b v1.0.0
 
 # dependency for https://github.com/erickt/rust-zmq
-RUN apt-get update && \
-    apt-get install -y --no-install-recommends libzmq3-dev \
-    && rm -rf /var/lib/apt/lists/*
+RUN apt-get install -y libzmq3-dev
 
 RUN echo '/opt/intel/sgxpsw/aesm/aesm_service &' >> /root/.bashrc
+
+ARG SGX_MODE
+
+RUN echo "#!/bin/bash \n\
+/opt/intel/sgxpsw/aesm/aesm_service \n\
+. /opt/sgxsdk/environment && . /root/.cargo/env && cd /root/enigma-core/enigma-core && SGX_MODE=$SGX_MODE RUSTFLAGS=-Awarnings make \n\
+cd /root/enigma-core/enigma-core/bin && ./app" > /root/compile_launch.bash
+RUN chmod +x /root/compile_launch.bash
+
+# Agressive build: we build it even it fails. Will always return true
+RUN cd enigma-core/enigma-core && . /opt/sgxsdk/environment && . /root/.cargo/env && SGX_MODE=$SGX_MODE RUSTFLAGS=-Awarnings make || true
+
+ENTRYPOINT ["/usr/bin/env"]
+CMD ["/bin/bash","-c","./compile_launch.bash; bash"]
